[package]
name = "atomr-view-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "atomr_view"
crate-type = ["cdylib"]

[dependencies]
atomr-view-core = { workspace = true }
atomr-view-backends = { workspace = true }
pyo3.workspace = true
tokio.workspace = true
log.workspace = true
